config/routes.rb
Examen1::Application.routes.draw do
  resources :clients do
    resources :phone_numbers, only: [:new, :create, :edit, :update]
  end

  root 'clients#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :phone_numbers

	def primary_number
		number = phone_numbers.primary.first
		number.present? ? number.number : "Sin Numero"
	end
end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  belongs_to :client

  scope :primary, -> { where(primary: true) }
  after_save :ensure_primary

  private
  	def ensure_primary
  		if self.primary?
  			self.client.phone_numbers.primary.where("id != ?",self.id).update_all(primary: false)
  		end
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
  	@clients = Client.order(:name)
  end

  def new
  	@client = Client.new
  end

  def create
  	@client = Client.new(client_params)

  	if @client.save
  		redirect_to clients_path
  	else
  		render :new
  	end
  end

  def edit
  	@client = Client.find(params[:id])
  end

  def update
  	@client = Client.find(params[:id])
  end

  def show
  	@client = Client.find(params[:id])
  end

  private
  	def client_params
  		params.require(:client).permit!
  	end
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  def new
 		@client = Client.find(params[:client_id])
 		@phone_number = PhoneNumber.new(primary: @client.phone_numbers.count == 0)
  end

  def create
  	@client = Client.find(params[:client_id])
  	@phone_number = @client.phone_numbers.build(phone_number_params)

  	if @phone_number.save
  		redirect_to @client
  	else
  		render :new
  	end
  end

  def edit
  end

  private

  	def phone_number_params
  		params.require(:phone_number).permit!
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/clients/_client.html.haml
%tr
	%td= client.id
	%td= link_to client.name, client
	%td= client.primary_number

app/views/clients/edit.html.haml
%h1 Clients#edit
%p Find me in app/views/clients/edit.html.haml

app/views/clients/index.html.haml
%h1 Clientes
%p Listado de clientes
#mi_tabla
  %table{border:"1"}
    %tr
      %th ID
      %th Nombre
      %th Numero Primario
    = render @clients
= link_to "Nuevo Cliente", new_client_path

app/views/clients/new.html.haml
%h1 Crear Cliente
%p Crea un nuevo cliente
= form_for @client do |f|
	.field
		= f.label :name
		=	f.text_field :name
	.field
		= f.label :email
		= f.email_field :email
	.field
		= f.submit
	

app/views/clients/show.html.haml
%h1= @client.name
%p
	%strong Email
	= @client.email
%h3 Listado de Telefonos
= render partial: "phone_numbers/table", locals: { numbers: @client.phone_numbers }
%ul
	%li= link_to "Editar", edit_client_path(@client)
	%li= link_to "Agregar Numero", new_client_phone_number_path(@client)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Examen1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="left-sidebar">
<div id="wrapper">
	<div id="content">
		<%= yield %>
	</div>
</div>
</body>
</html>

app/views/phone_numbers/_table.html.haml
%table
	%tr
		%th Numero
		%th Celular
		%th Primary
	- numbers.each do |phone_number|
		%tr
			%td= phone_number.number
			%td= phone_number.cellphone
			%td= phone_number.primary

app/views/phone_numbers/edit.html.haml
%h1 PhoneNumbers#edit
%p Find me in app/views/phone_numbers/edit.html.haml

app/views/phone_numbers/new.html.haml
%h1 Nuevo Telefono
%p Agregar un nuevo telefono
= form_for([@client, @phone_number]) do |f|
	.field
		= f.label :number
		= f.number_field :number
	.field
		= f.label :cellphone
		= f.text_field :cellphone

	.field{ style: @client.phone_numbers.count == 0 ? "display: none;" : "" }
		= f.check_box :primary
		= f.label :primary

	.field
		= f.submit